@echo off
chcp 65001 >nul
title Sunian - API Key Setup
cd /d "%~dp0sunian"

echo.
echo   ==================================================
echo     Sunian - API Key Setup
echo   ==================================================
echo.
echo   This writes your key into:  sunian\.env
echo   That file is excluded from git, so it stays private.
echo.
echo   --- Step 1 of 3: API Key (required) ---
set /p KEY="  API Key: "
if "%KEY%"=="" (
  echo.
  echo   Cancelled - no key entered.
  pause
  exit /b
)

echo.
echo   --- Step 2 of 3: Base URL (optional) ---
echo   Press Enter to use the default in config.json.
echo   DeepSeek official: https://api.deepseek.com/v1
set /p BASE="  Base URL: "

echo.
echo   --- Step 3 of 3: Model (optional) ---
echo   Press Enter to use the default in config.json.
echo   DeepSeek official example: deepseek-chat
set /p MODEL="  Model: "

echo # Sunian API config - generated by setup script > .env
echo SUNIAN_API_KEY=%KEY%>> .env
if not "%BASE%"=="" echo SUNIAN_BASE_URL=%BASE%>> .env
if not "%MODEL%"=="" echo SUNIAN_MODEL=%MODEL%>> .env

echo.
echo   ==================================================
echo   Saved to:  sunian\.env
echo.
echo   Contents (your key is shown here, do not screenshot):
type .env
echo   ==================================================
pause